version: '3.5'
services:
  database:
    container_name: mealplan_db
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    volumes: 
      - db_volume:/var/lib/postgresql

  app:
    container_name: mealplan
    build: app
    env_file: database.conf
    ports:
      - 5000:5000
    depends_on:
      - database

volumes:
  db_volume: