version: '2.1'
services:
  database:
    container_name: mealplan_db
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    volumes: 
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: mealplan
    build: app
    env_file: database.conf
    ports:
      - 5000:5000
      - 10001:10001 # debugging
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_volume: