version: '2.1'
services:
  database:
    container_name: mealplan_db
    image: postgres:13
    restart: always
    env_file: environment.conf
    ports:
      - 5432:5432
    volumes: 
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always

  celery_worker:
    container_name: celery_worker
    build: 
      context: app
      dockerfile: Dockerfile.dev
    command: celery -A application.cookidoo_celery_tasks worker --loglevel=info
    restart: always
    env_file: environment.conf
    depends_on:
      - redis

  app:
    container_name: mealplan
    image: ghcr.io/flecmart/mealplan:latest
    restart: always
    env_file: environment.conf
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      celery_worker:
        condition: service_started 

  backups:
    container_name: mealplan_backups
    image: prodrigestivill/postgres-backup-local:13-alpine-af916da
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    links:
        - database
    depends_on:
        - database
    env_file: environment.conf
    environment:
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

volumes:
  db_volume:
