FROM python:3.11
WORKDIR /app

# Set environment variables
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=password \
    POSTGRES_HOST=mealplan_db \
    POSTGRES_PORT=5432 \
    POSTGRES_DB=example \
    FLASK_SECRET=secret \
    TODOIST_TOKEN=123 \
    TODOIST_LIST=ShoppingList \
    SCREENSHOT_URL=https://duckduckgo.com/

# Install chromium
RUN apt-get update \
&& apt-get install -y chromium chromium-driver
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r requirements.txt
# download nltk data for natural language processing
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('averaged_perceptron_tagger')"
EXPOSE 5000
COPY . .
CMD ["pytest"]
