name: Cleanup docker images

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:

  cleanup:

    runs-on: ubuntu-latest

    steps:
    - name: Delete untagged ghcr
      uses: Chizkiyahu/delete-untagged-ghcr-action@v2
      with:
        token: ${{ secrets.PACKAGES_TOKEN }}
        untagged_only: true
        owner_type: user
